apiVersion: v1
kind: ServiceAccount
metadata:
  name: not-relevant
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice-svc
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: user-microservice
---
apiVersion: v1
kind: Service
metadata:
  name: order-microservice-svc
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 8080
  selector:
    app: order-microservice  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deploy
  labels:
    app: user-microservice  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      serviceAccountName: not-relevant
      containers:
      - env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "SERVER_TYPE"
          value: "http"                      
        - name: "NAME"
          value: "user-microservice"      
        - name: "MESSAGE"
          value: "Hello from user-microservice"    
        - name: "TIMING_VARIANCE"
          value: "40ms"                              
        - name: "TIMING_50_PERCENTILE"
          value: "150ms"                               
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nicholasjackson/fake-service:v0.17.0
        imagePullPolicy: IfNotPresent
        name: user-microservice
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice-deploy
  labels:
    app: order-microservice  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      serviceAccountName: not-relevant
      containers:
      - env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "SERVER_TYPE"
          value: "http"                      
        - name: "NAME"
          value: "order-microservice"      
        - name: "MESSAGE"
          value: "Hello from order-microservice"    
        - name: "TIMING_VARIANCE"
          value: "40ms"                              
        - name: "TIMING_50_PERCENTILE"
          value: "150ms"                               
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nicholasjackson/fake-service:v0.17.0
        imagePullPolicy: IfNotPresent
        name: order-microservice
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: shared-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "first.istiodemo.io"
    - "second.istiodemo.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: first-vs
spec:
  hosts:
  - "first.istiodemo.io"
  gateways:
  - shared-gateway
  http:
  - match:
    - uri:
        exact: /user
    route:
    - destination:
        host: user-microservice-svc
        port:
          number: 8000
  - match:
    - uri:
        exact: /order
    route:
    - destination:
        host: order-microservice-svc
        port:
          number: 9000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: second-vs
spec:
  hosts:
  - "second.istiodemo.io"
  gateways:
  - shared-gateway
  http:
  - match:
    - uri:
        exact: /user
    route:
    - destination:
        host: user-microservice-svc
        port:
          number: 8000
  - match:
    - uri:
        exact: /order
    route:
    - destination:
        host: order-microservice-svc
        port:
          number: 9000
