apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: shared-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "silentretries.istiodemo.io"
    - "noretries.istiodemo.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-with-retries-vs
spec:
  hosts:
  - "silentretries.istiodemo.io"
  gateways:
  - shared-gateway
  http:
  - match:
    - uri:
        exact: /bff
    route:
    - destination:
        host: bff-svc
        port:
          number: 8000
  - match:
    - uri:
        exact: /backend
    route:
    - destination:
        host: backend-faulty-svc
        port:
          number: 8000
    retries:
      attempts: 3
      retryOn: connect-failure,refused-stream,503,500
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: internal-backend-with-retries-vs
spec:
  hosts:
  - backend-faulty-svc
  http:
  - route:
    - destination:
        host: backend-faulty-svc
        port:
          number: 8000
    retries:
      attempts: 3
      retryOn: connect-failure,refused-stream,503,500
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-backend-without-retries-vs
spec:
  hosts:
  - "noretries.istiodemo.io"
  gateways:
  - shared-gateway
  http:
  - route:
    - destination:
        host: backend-faulty-svc
        port:
          number: 8000
--- 
apiVersion: v1
kind: Service
metadata:
  name: bff-svc
  labels:
    app: bff
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: bff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      serviceAccountName: backend
      containers:
      - env:
        - name: "UPSTREAM_URIS"
          value: "http://backend-faulty-svc.default.svc.cluster.local:8000/"    
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "SERVER_TYPE"
          value: "http"                      
        - name: "NAME"
          value: "bff"      
        - name: "MESSAGE"
          value: "hello from bff with retries enabled"              
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nicholasjackson/fake-service:v0.17.0
        name: bff
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: backend-faulty-svc
  labels:
    app: backend-faulty
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-faulty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-faulty
  labels:
    app: backend-faulty  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-faulty
  template:
    metadata:
      labels:
        app: backend-faulty
    spec:
      serviceAccountName: backend
      containers:
      - env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "SERVER_TYPE"
          value: "http"                      
        - name: "NAME"
          value: "backend"      
        - name: "MESSAGE"
          value: "hello from faulty backend"               
        - name: "ERROR_CODE"
          value: "500"
        - name: "ERROR_RATE"
          value: "0.5"        
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nicholasjackson/fake-service:v0.17.0
        name: backend
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend