apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: shared-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "timeout.istiodemo.io"
    - "notimeout.istiodemo.io"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bff-vs
spec:
  hosts:
  - "timeout.istiodemo.io"
  gateways:
  - shared-gateway
  http:
  - match:
    - uri:
        exact: /bff
    route:
    - destination:
        host: bff-svc
        port:
          number: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-backend-with-timeout-vs
spec:
  hosts:
  - "timeout.istiodemo.io"
  gateways:
  - shared-gateway
  http:
  - match:
    - uri:
        exact: /backend
    route:
    - destination:
        host: backend-slow-svc
        port:
          number: 8000
    timeout: 0.5s
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: external-backend-without-timeout-vs
spec:
  hosts:
  - "notimeout.istiodemo.io"
  gateways:
  - shared-gateway
  http:
  - match:
    - uri:
        exact: /backend
    route:
    - destination:
        host: backend-slow-svc
        port:
          number: 8000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: internal-backend-with-timeout-vs
spec:
  hosts:
  - backend-slow-svc
  http:
  - route:
    - destination:
        host: backend-slow-svc
        port:
          number: 8000
    timeout: 0.5s
--- 
apiVersion: v1
kind: Service
metadata:
  name: backend-slow-svc
  labels:
    app: backend
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
--- 
apiVersion: v1
kind: Service
metadata:
  name: bff-svc
  labels:
    app: bff
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: bff
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      serviceAccountName: backend
      containers:
      - env:
        - name: "UPSTREAM_URIS"
          value: "http://backend-slow-svc.default.svc.cluster.local:8000/"    
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "SERVER_TYPE"
          value: "http"                      
        - name: "NAME"
          value: "bff"      
        - name: "MESSAGE"
          value: "hello from bff"              
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nicholasjackson/fake-service:v0.17.0
        name: backend
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-slow
  labels:
    app: backend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
      - env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:8080"
        - name: "SERVER_TYPE"
          value: "http"                      
        - name: "NAME"
          value: "backend"      
        - name: "MESSAGE"
          value: "hello from backend"               
        - name: "TIMING_50_PERCENTILE"
          value: "1000ms"                                
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: nicholasjackson/fake-service:v0.17.0
        name: backend
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend